version: '3'

services:
  server-api:
    build: ./server_api
    volumes:
      - ./server_api:/usr/src/app
    ports:
      - 5001:80

  client:
    build: ./client
    volumes:
      - ./client:/usr/src/app
    ports:
      - 5002:80
